name: publish

on:
  release:
    types: [published]

jobs:
  build:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build wheels
        run: |
          poetry build
      - name: Upload to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi dummy # Necessary otherways poetry doesn't
          # look for the token in the environment variables.
          poetry publish
